/**
 * ESP32 secrets file
 * 
 * Contains information required to connect to WiFi and in-turn, AWS IoT
 * 
 * Authors: Vipul Deshpande, Jaime Burbano
 */


/*
  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
  Permission is hereby granted, free of charge, to any person obtaining a copy of this
  software and associated documentation files (the "Software"), to deal in the Software
  without restriction, including without limitation the rights to use, copy, modify,
  merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
  permit persons to whom the Software is furnished to do so.
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
  INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
  PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


#include <pgmspace.h>

#define SECRET
#define THINGNAME "Your Thing Name"

const char WIFI_SSID[] = "Your WiFi SSID";
const char WIFI_PASSWORD[] = "Your WiFi Password";
const char AWS_IOT_ENDPOINT[] = "Your AWS IoT Endpoint";

/* Amazon Root CA 1 */
static const char AWS_CERT_CA[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----
)EOF";

/* Device Certificate */
static const char AWS_CERT_CRT[] PROGMEM = R"KEY(
-----BEGIN CERTIFICATE-----
MIIDWjCCAkKgAwIBAgIVAPZwhnwgxqtmCmnoUu0EziMduD8AMA0GCSqGSIb3DQEB
CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t
IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0yMDEwMTcyMTQ1
NTFaFw00OTEyMzEyMzU5NTlaMB4xHDAaBgNVBAMME0FXUyBJb1QgQ2VydGlmaWNh
dGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDLEE2u/rTGq1oUnRGx
QcqemMwgaPSzxD1D3KN7/L/gpUx+2dtAxUKOF3wSUJWXy3PbGfbtlhmhmPcrNxWV
aLcSM8PJA2GhAXaaTOkJ9VXJKEnLeUFWMnpkfhvGFv2GhLumTAKylAyA2/P48wkS
HBcrHTd3rUANhVb4CxItwWEjd8rsmHrZ4NUC8Sny/527TpxqqDK0wqs9KvfGW1qA
hO0tnW3iJoggv6skJEmOudaZhDjZOwYpDCS4nt1rLIAOT1eu4J5ESmbGIED6y2m8
0FBR6Ymbv94SKnMzIO6iYu46CZHAfglwXdcgEjudX4M1HQRLW9t0k6l3mAZiDDKK
2KkVAgMBAAGjYDBeMB8GA1UdIwQYMBaAFFQQW8nRfU70ov1CETg3wsFc0SpjMB0G
A1UdDgQWBBRvXBPBUVXo9JnJadckXqsRszwMATAMBgNVHRMBAf8EAjAAMA4GA1Ud
DwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAQEAQm9jOHScWaDrLWquEQQ+lJgT
BXQBwD7zMEF+KagqDHAw5ZkMzPpYqRCE4gM45hClJblpwyquH2GeSQxnwYz+7SVl
vF8zj4ID6krrsl0YIUPw120INfHbLzVT1TCcQ1iZElZ7aF6KuxgWkwIkmr3+4M/a
QjuEVKHMuz5DnvZNBQv5+Ui7XIGfKwiC3QrJhxFCBJBOczlnssm2y8OlL9S994Fv
p10lK2Pf/7oY+GXkJHwlsPnDlPTeOKYHygJ3jdB8jGFZuOv3lE6ikWbzl69Vmcwq
MxKZIQQulTk48teViVzv3oLfW8Da1fxY/xh7H/+wVTu2v5+QbINopcvoVfUeTg==
-----END CERTIFICATE-----
)KEY";

/* Device Private Key */
static const char AWS_CERT_PRIVATE[] PROGMEM = R"KEY(
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAyxBNrv60xqtaFJ0RsUHKnpjMIGj0s8Q9Q9yje/y/4KVMftnb
QMVCjhd8ElCVl8tz2xn27ZYZoZj3KzcVlWi3EjPDyQNhoQF2mkzpCfVVyShJy3lB
VjJ6ZH4bxhb9hoS7pkwCspQMgNvz+PMJEhwXKx03d61ADYVW+AsSLcFhI3fK7Jh6
2eDVAvEp8v+du06caqgytMKrPSr3xltagITtLZ1t4iaIIL+rJCRJjrnWmYQ42TsG
KQwkuJ7dayyADk9XruCeREpmxiBA+stpvNBQUemJm7/eEipzMyDuomLuOgmRwH4J
cF3XIBI7nV+DNR0ES1vbdJOpd5gGYgwyitipFQIDAQABAoIBADf3q2GTBCJJsg9C
Z1DysDTcKk64ftFZQgWFN24B8KSrCpVf2EVW2QwuvtyRZ1mqEqmN03gSScg3T9CS
YxmF/gc/SzQJAYyNybGnhwdeniFOQGCbb/2g9gjilScYyRGdXdbs1kV/9p5BgVHZ
MmPSaDRS3inXD3Nqj9jXvE/uH6bVbDl2bD7criBGMvC1OEx3QtNo8Sahi2eor9hx
e4+OKhGj+J5jwLCdgfS4UbROUi0JzGqytPseVwWuNm9bMi3obBEoPID9/sut7Q6F
aFWs39+4GLSoIM8Cx1xw4wQ8T6HzHqU2qrEsZkbMg1g9DKb7pP2OA9S/bHekkrJi
ftySLYECgYEA/J/VjN5x7Wokr+DEQz3gVh5UoHMLhI9Zh0HecGK33sWP76Ya7VdX
sNk+kKz3F9vNw+JwSZ0AjY0YPZd3ufgFlkAe6ggCAG4fdVEor9R9Jl7UEUqypB1f
NqX/GJ6F1zxyxt4WUFUadBOasalsgO3oU/uVv8ovfxFRZN+UjC1PTyECgYEAzcbv
NYHgL8O1dRy0AT/bYq0oNZaHWKm07mWZ5cAuOqRXqz3eSyyG0spOJ3njpaaDM8bx
hHCsZBsVElkMIE74VZIgkPFCk+1xcXnWyMX+7Z9aOsEWrEVFmP8FEsHXyoaOhX2T
pTXdKuh8U8Kmu8E2s5xrV1Xu2xaukWyf6Sj0n3UCgYEAoo1OYhh4gmX8OVeNsh7M
jV1y4tNkI+YBm7DcqsA6xBOnrHLbfMDo4hjH01wYmreKzXKVAikORAb4BBnEpltb
bPTRb5G7h/9UKq8QWSOHa/s0xfOkw0lLDOT/Ih5OzNJOoHwjK4m3Pd2neo4kDUoI
ZpHKJ+C3czH3h8r90L0O/UECgYA73iPcQmPyIZNadjZcorJ2PACVzqyj/APa1A55
THdmskebV42j+1liXF9ulsTHffFwD/JWYN2W5lY0F1oy0Cbp5nC5GqgPF6bIp/T4
RrqLcbAzpdet2R2NjKxyL5lTn+A5MDbTex9Ui30YdWpC98ytZtXH/AVZEnlJb/v6
PuMkvQKBgQCIBSq5lu623ZD9v8C7hNf9p1J4ejM4ZhKBVJEoGQ2+tHSTbkYy72JH
bJr7l92Usr1pi3gypxawNREZOUixfuQa3cSfqvHAK8tr5zHEvJ6ksTXlcscwm15H
RD8QeXGpGwvFbqHAT9RmCGeTAlWVUDJCm3KH+SCf8lUZCfjNrNSp9Q==
-----END RSA PRIVATE KEY-----
)KEY";